include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    always_put_required_named_parameters_first: false

    prefer_single_quotes: true
    directives_ordering: true
    prefer_relative_imports: true
    sort_pub_dependencies: false

analyzer:
  exclude:
    - lib/l10n/*
