name: ixir_app
description: Love connects your family. iXir connects your health.

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1

  #state management
  flutter_bloc: ^6.0.5
  equatable: ^1.2.5

  #firebase
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  firebase_storage: ^7.0.0
  firebase_crashlytics: ^0.4.0+1

  responsive_builder: ^0.3.0

  country_code_picker: ^1.7.0
  date_field: ^2.0.0
  get_it: ^5.0.1
  font_awesome_flutter: ^8.8.1
  email_validator: ^1.0.6
  enum_to_string: ^1.0.14
  flutter_svg: ^0.19.3
  fluttertoast: ^7.1.8

  lorem_ipsum: any
  sized_context: ^0.2.1+1
  shared_preferences: ^0.5.12+4
  google_fonts: ^1.1.2
  dropdown_formfield: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint: ^1.5.3
  flutter_launcher_icons: ^0.8.1

dependency_overrides:
  intl: ^0.17.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
